sylius_resource:
    resources:
        acme.post:
            driver: doctrine/orm
            classes:
                model: DemoBundle\Entity\Post
        acme.forum:
            driver: doctrine/orm
            classes:
                model: DemoBundle\Entity\Forum
        acme.sujet:
            driver: doctrine/orm
            classes:
                model: DemoBundle\Entity\Sujet



fos_rest:
    disable_csrf_role: ROLE_API
    view:
        formats:
            json: true
            xml:  true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }
