DemoBundle\Entity\Forum:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
    manyToOne:
        auteur:
            targetEntity: DemoBundle\Entity\Auteur
            joinColumn:
                name: auteur_id
                referencedColumnName: id        
    lifecycleCallbacks: {  }
