DemoBundle\Entity\Sujet:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
    manyToOne:
        auteur:
            targetEntity: DemoBundle\Entity\Auteur
            joinColumn:
                name: auteur_id
                referencedColumnName: id      
    manyToOne:
        forum:
            targetEntity: DemoBundle\Entity\Forum
            joinColumn:
                name: forum_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
